version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3"
  jobs:
    post_checkout:
      - (git --no-pager log --pretty="tformat:%s" -1 | grep -vqF "[skip-rtd]") || exit 183
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged docs/conf.py docs/requirements.txt

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  fail_on_warning: true
  configuration: docs/conf.py
